sudo: false
language: ruby
cache: bundler

matrix:
  include:
    - rvm: 2.3.6
    - rvm: 2.4.3
    - rvm: 2.5.0
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head
branches:
  only:
  - master

bundler_args: --without changelog

before_install:
  - gem install bundler
  - bundle --version
  - gem update --system
  - gem --version

script:
  - bundle exec rake ci
