sudo: false
language: ruby
cache: bundler

addons:
  apt:
    packages:
      - libarchive-dev

matrix:
  include:
    - rvm: 2.3.8
    - rvm: 2.4.5
    - rvm: 2.5.3
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head

branches:
  only:
  - master

bundler_args: --without docs debug

before_install:
  - gem install bundler
  - bundle --version
  - gem update --system
  - gem --version

script: bundle exec rake
